name: BetterCommands
version: V1.0 Build 001
authors: [Robins Tech-Projects, FroznMine]
website: robins-techprojects.blogspot.com
main: com.blogspot.robinstechprojects.BCP.BCPMain
commands: 
  h:
    description: Heilt den Spieler 
    usage: /h
  gm2:
    description: Setzt den Gamemode auf ADVENTURE
    usage: /gm2
    permission: bcp.gm2
  gm0:
    description: Setzt den Gamemode auf SURVIVAL
    usage: /gm0
    permission: bcp.gm0
  gm1:
    description: Setzt den Gamemode auf CREATIVE
    usage: /gm1
    permission: bcp.gm1
  xpf:
    description: Fuellt die Erfahrung um 1000 auf
    usage: /xpf
    permission: bcp.xp
  food:
    description: Fuellt dem Spieler die Essens Punkte auf!
    usage: /food
    permission: bcp.eat
  bio:
    description: Zeigt dem Spieler das Biom an in dem er sich befindet
    usage: /bio
    permission: bcp.bio 
  bcp:
    description: Prueft ob BCP Funktioniert
    usage: /bcp
    permission:
  bettercommands:
    description: Prueft ob BCP Funktioniert
    usage: /bettercommands
    permission:
 
