name: BetterCommands
version: Beta1.4
authors: [Iborn LP, FroznMine]
website: ibornlp.jimdo.com


main: bcp.BCP
commands: 
     h:
      description: Heilt den Spieler 
      usage:
     gm2:
      description: Setzt den Gamemode auf ADVENTURE
      usage:
     gm0:
      description: Setzt den Gamemode auf SURVIVAL
      usage:   
     gm1:
      description: Setzt den Gamemode auf CREATIVE
      usage:
     xpf:
      description: Füllt die Erfahrung um 1000 auf
      usage:
     food:
      description: Füllt dem Spieler die Essens Punkte auf!
      usage:   
      
     
